[build]
  base = "frontend"
  publish = "build/web"
  command = """
    wget -q https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.5-stable.tar.xz
    tar -xf flutter_linux_3.22.5-stable.tar.xz
    export PATH="$PATH:$(pwd)/flutter/bin"
    flutter pub get
    flutter build web --release
  """
