[build]
  base = "."
  publish = "frontend/build/web"
  command = """
    ./frontend/build.sh
  """

[build.environment]
  API_URL = "https://esmnst.onrender.com/api"
  FIREBASE_API_KEY = "AIzaSyCrDFrYcZ18IksAvlAGXjZGv-M--5kL-mM"
  FIREBASE_AUTH_DOMAIN = "esimnest-prod.firebaseapp.com"
  FIREBASE_PROJECT_ID = "esimnest-prod"
  FIREBASE_STORAGE_BUCKET = "esimnest-prod.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID = "738532349365"
  FIREBASE_APP_ID = "1:738532349365:web:YOUR_APP_ID"
