services:
  - type: web
    name: esmnst-frontend
    env: static
    buildCommand: |
      curl -sS https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -o tools.zip
      unzip tools.zip
      mv cmdline-tools tools
      echo 'export PATH="$PATH:`pwd`/tools/bin"' >> ~/.bashrc
      ./tools/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"
      git clone https://github.com/flutter/flutter.git -b stable
      export PATH="$PATH:`pwd`/flutter/bin"
      flutter pub get
      flutter build web --release
      mkdir -p /opt/render/static
      cp -r build/web/* /opt/render/static
    staticPublishPath: /opt/render/static
    envVars:
      - key: API_URL
        value: https://esmnst.onrender.com
